-- ============================================
-- ScholarSync - Smart Library & Academic Assistant
-- Local Database Schema (XAMPP / MySQL)
-- ============================================
-- Run: npm start  (schema is auto-created by the server)
-- Or import this file manually via phpMyAdmin

CREATE DATABASE IF NOT EXISTS library_management;
USE library_management;

-- Users table (admin & student accounts)
CREATE TABLE IF NOT EXISTS users (
  id       INT PRIMARY KEY AUTO_INCREMENT,
  name     VARCHAR(100) NOT NULL,
  email    VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role     VARCHAR(20)  NOT NULL
);

-- Books inventory catalog
CREATE TABLE IF NOT EXISTS books (
  id        INT PRIMARY KEY AUTO_INCREMENT,
  title     VARCHAR(255) NOT NULL,
  author    VARCHAR(255) NOT NULL,
  category  VARCHAR(100) NOT NULL,
  quantity  INT NOT NULL,
  available INT NOT NULL
);

-- Borrow / return transaction log
CREATE TABLE IF NOT EXISTS transactions (
  id          INT PRIMARY KEY AUTO_INCREMENT,
  user_id     INT  NOT NULL,
  book_id     INT  NOT NULL,
  issue_date  DATE NOT NULL,
  due_date    DATE NOT NULL,
  return_date DATE NULL,
  INDEX idx_trans_user (user_id),
  INDEX idx_trans_book (book_id)
);

-- 12-hour book reservation queue
CREATE TABLE IF NOT EXISTS reservations (
  id               INT PRIMARY KEY AUTO_INCREMENT,
  user_id          INT      NOT NULL,
  book_id          INT      NOT NULL,
  reservation_date DATETIME NOT NULL,
  INDEX idx_res_user (user_id),
  INDEX idx_res_book (book_id)
);

-- ═══════════════════════════════════════════════════════════
-- Smart Library & Academic Assistant Tables
-- ═══════════════════════════════════════════════════════════

-- Uploaded PDF textbooks / study materials
CREATE TABLE IF NOT EXISTS ebooks (
  id          INT PRIMARY KEY AUTO_INCREMENT,
  title       VARCHAR(255) NOT NULL,
  subject     VARCHAR(150) NOT NULL,
  file_path   VARCHAR(500) NOT NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Searchable text chunks extracted from each ebook
CREATE TABLE IF NOT EXISTS ebook_chunks (
  id          INT PRIMARY KEY AUTO_INCREMENT,
  ebook_id    INT NOT NULL,
  chunk_text  MEDIUMTEXT NOT NULL,
  chunk_index INT NOT NULL DEFAULT 0,
  INDEX idx_chunk_ebook (ebook_id),
  FULLTEXT INDEX ft_chunk_text (chunk_text)
);

-- Student answer history generated by the AI assistant
CREATE TABLE IF NOT EXISTS generated_answers (
  id             INT PRIMARY KEY AUTO_INCREMENT,
  user_id        INT NOT NULL,
  question       TEXT NOT NULL,
  answer         LONGTEXT NOT NULL,
  marks          INT NOT NULL,
  source_book    VARCHAR(255),
  source_chapter VARCHAR(255),
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ga_user (user_id)
);

